"""Constants"""
WINSIZE = (850, 700)
FRAME_PATTERN = r'\.\d{1,10}'

FOLDER_ENTRY_WIDTH = 620
RANGE_ENTRY_WIDTH = 100

METHOD_OPTIONS = ['Sobel', "All", "Any", "Temporal"]
CHAN_OPTIONS = ['R', 'G', 'B', 'A', 'Z', 'QC']

SEQ_HEIGHT = 175
SEQ_WIDTH = 800

LOG_HEIGHT = 320
LOG_WIDTH = 800
